sudo: required
services:
   - docker
before_install:
   - docker build -t nareshvj/docker-react -f Dockerfile.dev .
deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "docker"
   env: "Docker"
   bucket_name: "elasticbeanstalk-us-east-1-934379134944"
   bucket_path: "docker"
   on:
      branch: master   
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
      secure: "$AWS_SECRET_KEY"